steam_install_path: 'C:\Program Files (x86)\Steam'
steam_library_locations:
  - 'C:\Program Files (x86)\Steam\steamapps'
  - 'D:\SteamLibrary\steamapps'
skip_appids:
  - '228980' # https://steamdb.info/app/228980
  - '404790' # Godot engine
